<a href="https://colab.research.google.com/github/qamarsatti/MSAI/blob/main/Lab_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import pandas as pd

In [63]:
df=pd.read_csv('reviews_dataset.csv')

In [64]:
df.head()

                                                news      type
0  China had role in Yukos split-up\n \n China le...  business
1  Oil rebounds from weather effect\n \n Oil pric...  business
2  Indonesia 'declines debt freeze'\n \n Indonesi...  business
3  $1m payoff for former Shell boss\n \n Shell is...  business
4  US bank in $515m SEC settlement\n \n Five Bank...  business

In [65]:


import re

def remove_non_alphabetic_words(text):
  # Use regular expressions to remove non-alphabetic words
  words = re.findall(r'\b[a-zA-Z]+\b', text)
  return " ".join(words)

# Apply the function to the 'news' column
df['news'] = df['news'].apply(remove_non_alphabetic_words)

In [66]:
df['news']

0       China had role in Yukos split up China lent Ru...
1       Oil rebounds from weather effect Oil prices re...
2       Indonesia declines debt freeze Indonesia no lo...
3       payoff for former Shell boss Shell is to pay t...
4       US bank in SEC settlement Five Bank of America...
                              ...
2220    Microsoft launches its own search Microsoft ha...
2221    Warnings about junk mail deluge The amount of ...
2222    Microsoft gets the blogging bug Software giant...
2223    Gamers snap up new Sony PSP Gamers have bought...
2224    Apple laptop is greatest gadget The Apple Powe...
Name: news, Length: 2225, dtype: object

In [67]:
# prompt: convert df['news'] in into lower

df['news'] = df['news'].str.lower()
df['news']

0       china had role in yukos split up china lent ru...
1       oil rebounds from weather effect oil prices re...
2       indonesia declines debt freeze indonesia no lo...
3       payoff for former shell boss shell is to pay t...
4       us bank in sec settlement five bank of america...
                              ...
2220    microsoft launches its own search microsoft ha...
2221    warnings about junk mail deluge the amount of ...
2222    microsoft gets the blogging bug software giant...
2223    gamers snap up new sony psp gamers have bought...
2224    apple laptop is greatest gadget the apple powe...
Name: news, Length: 2225, dtype: object

In [68]:
print(df['type'].value_counts())

type
sport            511
business         510
politics         417
tech             401
entertainment    386
Name: count, dtype: int64

In [69]:
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize,sent_tokenize

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [70]:

#df['sentences'] = df['review'].apply(sent_tokenize)
df['news'] = df['news'].apply(word_tokenize)

In [71]:
df.head()

                                                news      type
0  [china, had, role, in, yukos, split, up, china...  business
1  [oil, rebounds, from, weather, effect, oil, pr...  business
2  [indonesia, declines, debt, freeze, indonesia,...  business
3  [payoff, for, former, shell, boss, shell, is, ...  business
4  [us, bank, in, sec, settlement, five, bank, of...  business

In [72]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmitizer = WordNetLemmatizer()
def lemmitize_words(text):
    return " ".join([lemmitizer.lemmatize(word,pos='v') for word in text.split()])

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [73]:

def lemmatize_words(tokens):
    return [lemmitizer.lemmatize(word,pos='v') for word in tokens]
    #return " ".join([lemmatizer.lemmatize(word) for word in tokens])

# Lemmatizing the tokenized words in the 'review' column
df['lemmatized_news'] = df['news'].apply(lemmatize_words)

In [74]:
df.head()

,news,type,lemmatized_news
0,"[china, had, role, in, yukos, split, up, china...",business,"[china, have, role, in, yukos, split, up, chin..."
1,"[oil, rebounds, from, weather, effect, oil, pr...",business,"[oil, rebound, from, weather, effect, oil, pri..."
2,"[indonesia, declines, debt, freeze, indonesia,...",business,"[indonesia, decline, debt, freeze, indonesia, ..."
3,"[payoff, for, former, shell, boss, shell, is, ...",business,"[payoff, for, former, shell, boss, shell, be, ..."
4,"[us, bank, in, sec, settlement, five, bank, of...",business,"[us, bank, in, sec, settlement, five, bank, of..."

In [75]:

from sklearn.preprocessing import LabelEncoder

X = df.drop('news', axis=1)
X = df['lemmatized_news']
Y = df['type']

print(X)
print(Y)

encoder = LabelEncoder()
Y = encoder.fit_transform(Y)

0       [china, have, role, in, yukos, split, up, chin...
1       [oil, rebound, from, weather, effect, oil, pri...
2       [indonesia, decline, debt, freeze, indonesia, ...
3       [payoff, for, former, shell, boss, shell, be, ...
4       [us, bank, in, sec, settlement, five, bank, of...
                              ...
2220    [microsoft, launch, its, own, search, microsof...
2221    [warnings, about, junk, mail, deluge, the, amo...
2222    [microsoft, get, the, blogging, bug, software,...
2223    [gamers, snap, up, new, sony, psp, gamers, hav...
2224    [apple, laptop, be, greatest, gadget, the, app...
Name: lemmatized_news, Length: 2225, dtype: object
0       business
1       business
2       business
3       business
4       business
          ...
2220        tech
2221        tech
2222        tech
2223        tech
2224        tech
Name: type, Length: 2225, dtype: object

In [76]:

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [77]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [78]:

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()


X_train_g = [" ".join(words) for words in X_train]
X_test_g = [" ".join(words) for words in X_test]

X_train_vec = vectorizer.fit_transform(X_train_g)
X_test_vec = vectorizer.transform(X_test_g)

In [79]:
rf = RandomForestClassifier(n_estimators=150)

rf.fit(X_train_vec,y_train)
y_pred = rf.predict(X_test_vec)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

0.9483146067415731
[[109   0   5   0   1]
 [  3  64   2   1   2]
 [  4   0  72   0   0]
 [  0   0   0 102   0]
 [  4   1   0   0  75]]

In [80]:
vectorizer = CountVectorizer(ngram_range=(2, 2)) # Use ngram_range to specify bigrams

X_trainbi = [" ".join(words) for words in X_train]
X_testbi = [" ".join(words) for words in X_test]

X_train_vec_bi = vectorizer.fit_transform(X_trainbi)
X_test_vec_bi = vectorizer.transform(X_testbi)

In [81]:
rf = RandomForestClassifier(n_estimators=150)
rf.fit(X_train_vec_bi,y_train)
y_pred = rf.predict(X_test_vec_bi)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

0.8786516853932584
[[107   0   4   3   1]
 [  8  51   0  11   2]
 [  2   0  68   6   0]
 [  1   0   0 101   0]
 [  9   1   0   6  64]]

In [82]:
# prompt: apply trigram  on this

vectorizer = CountVectorizer(ngram_range=(3, 3)) # Use ngram_range to specify trigrams

X_traintri = [" ".join(words) for words in X_train]
X_testtri = [" ".join(words) for words in X_test]

X_train_vec_tri = vectorizer.fit_transform(X_traintri)
X_test_vec_tri = vectorizer.transform(X_testtri)

In [83]:
rf = RandomForestClassifier(n_estimators=150)
rf.fit(X_train_vec_tri,y_train)
y_pred = rf.predict(X_test_vec_tri)

print (accuracy_score(y_test,y_pred))
print (confusion_matrix(y_test,y_pred))

0.797752808988764
[[102   1   3   7   2]
 [ 17  37   0  18   0]
 [  6   0  62   6   2]
 [  0   0   0 102   0]
 [ 16   3   0   9  52]]